name: Go CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install dependencies
        run: go mod download

      - name: Check formatting
        run: |
          go fmt ./...
          git diff --exit-code

      - name: Run vet
        run: go vet ./...

      - name: Run tests
        run: go test -v ./...